### ISSUE TITLE
MOSMIX_L Error - Use in Solaranzeige Docker Image

### ISSUE THREAD

**Issue by etofi** [StefaE/PVForecast#22]
Since the last update I only have this in the log and no more values in the DB.

`Error: Can't run MOSMIX_L - pvlib library installation missing or old version (required: >=0.9.0)`

pvlib is installed

```
root@01ae52cb3939:/pvforecast# pip show pvlib
Name: pvlib
Version: 0.10.1
Summary: A set of functions and classes for simulating the performance of photovoltaic systems.
Home: https://github.com/pvlib/pvlib-python
Author: pvlib python Developers
Author email: 
Licence: BSD 3 clause
Location: /usr/local/lib/python3.9/dist-packages
Needed by: h5py, numpy, pandas, pytz, requests, scipy
Needed by: 
```

**Comment by StefaE** [comment]
sorry for that... version checking was not handling 0.9.x < 0.10.x correctly :-( I fixed that in v2.11.01.

Just in case: I'm now library `packaging` for version comparison. This should most likely be available everywhere. But if not, `pip install packaging` will install it.

**Comment by etofi** [comment]
I have installed the update - unfortunately still the same error message.
